services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
        HOST: ${HOST}
        DATABASE_URL: ${DATABASE_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        INTERNAL_API_TOKEN: ${INTERNAL_API_TOKEN}
        API_URL_SERVER: ${API_URL_SERVER}
        CRON_SECRET: ${CRON_SECRET}
        CREDIT_BALANCE_SECRET: ${CREDIT_BALANCE_SECRET}
    container_name: a-w-vpn-next-app
    restart: always
    ports:
      - '3001:3000' # наружу -> внутрь
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY}
      HOST: ${HOST}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      INTERNAL_API_TOKEN: ${INTERNAL_API_TOKEN}
      API_URL_SERVER: ${API_URL_SERVER}
      CRON_SECRET: ${CRON_SECRET}
      CREDIT_BALANCE_SECRET: ${CREDIT_BALANCE_SECRET}
