allowBuilds:
  '@prisma/engines': set this to true or false
  bcrypt: set this to true or false
  msw: true
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
